--  Update the phone number of customer with ID 2.
UPDATE customers
SET phone='9876543210'
WHERE customer_id=2;

-- Display complete purchase history of each customer.
SELECT c.customer_name,p.product_name,s.sales_date,s.amount
FROM customers c
JOIN sales s
ON c.customer_id = s.customer_id
JOIN products p
ON s.product_id = p.product_id;

-- Display customers along with their contact person details.
SELECT c.customer_name,ct.contact_name,ct.phone
FROM customers c
JOIN contacts ct
ON c.customer_id = ct.customer_id;

-- Display customers who have purchased products worth more than ₹4500.
SELECT DISTINCT c.customer_name,s.amount
FROM customers c
JOIN sales s
ON c.customer_id = s.customer_id
WHERE s.amount > 4500;

-- Display total amount spent by each customer.
SELECT c.customer_name,SUM(s.amount) AS total_amount
FROM customers c
JOIN sales s
ON c.customer_id = s.customer_id
GROUP BY c.customer_name;

-- Display all available products with their prices.
SELECT *
FROM products;

-- Find products priced above the average price.
SELECT *
FROM products
WHERE price >
(
SELECT AVG(price)
FROM products
);

-- Display revenue generated by each product
SELECT p.product_name,SUM(s.amount) AS revenue
FROM products p
JOIN sales s
ON p.product_id = s.product_id
GROUP BY p.product_name;

-- Find the highest-selling product.
SELECT p.product_name,COUNT(*) AS total_sales
FROM products p
JOIN sales s
ON p.product_id = s.product_id
GROUP BY p.product_name
ORDER BY total_sales DESC
LIMIT 1;

-- Display products that have never been sold.
SELECT product_name
FROM products
WHERE product_id NOT IN
(
SELECT product_id
FROM sales
);

-- Display monthly sales revenue.
SELECT MONTH(sales_date) AS month,SUM(amount) AS revenue
FROM sales
GROUP BY MONTH(sales_date);

-- Display total number of sales made by each employee.
SELECT e.employee_name,COUNT(s.sales_id) AS sales_count
FROM employees e
JOIN sales s
ON e.employee_id = s.employee_id
GROUP BY e.employee_name;

-- Count employees in each department.
SELECT department,COUNT(*) AS total_employees
FROM employees
GROUP BY department;

-- Count interactions handled by each employee.
SELECT e.employee_name,COUNT(*) AS interactions
FROM employees e
JOIN interactions i
ON e.employee_id = i.employee_id
GROUP BY e.employee_name;

-- Display interaction count based on interaction type.
SELECT interactiontype,COUNT(*) AS total
FROM interactions
GROUP BY interactiontype;

-- Display customer support tickets.
SELECT c.customer_name,st.issues,st.status
FROM support_tickets st
JOIN customers c
ON st.customer_id = c.customer_id;

-- Display all open support tickets.
SELECT *
FROM support_tickets
WHERE status = 'Open';

-- Calculate average customer rating.
SELECT ROUND(AVG(rating),2) AS average_rating
FROM feedback;

-- Display lead source analysis.
SELECT source,COUNT(*) AS total_leads
FROM leads
GROUP BY source;

-- Display rating distribution.
SELECT rating,COUNT(*) AS total_customers
FROM feedback
GROUP BY rating
ORDER BY rating DESC;


















